#!/bin/bash
#@aboriginal build [target]
#@ - Build a specific target using all stages
#@aboriginal build [target] [stage]
#@ - Build a specified target starting from a certain stage
[ -z $VER ] && echo "$0 is a helper file" && exit 1
[ "$1" = "$$BASH_SOURCE" ] && show_usage $BASH_SOURCE

echo $BASH_SOURCE

# set export variables
export TARGET="$1"
export STAGE="$2"

# set local variables
local _STAGES=($(ls $DIR_STGS/$([ -n "$STAGE" ] && echo $STAGE* $DIR_STGS/[0-9][0-9]-$STAGE*) 2>/dev/null))
local _START=$(basename "${_STAGES[0]}")
local _STARTED=0

show_header

# loop through stages only do from starting stage
for FILE_STAGE in $(ls $DIR_STGS); do
  [ "$FILE_STAGE" = "$_START" ] && _STARTED=1
  [ $_STARTED = 1 ] && aborignal stage $FILE_STAGE $TARGET
done

echo
