#!/bin/bash
#@call build [target]
#@ - Build a specific target using all stages
#@call build [target] [stage]
#@ - Build a specified target starting from a certain stage
[ -z $VER ] && echo "$0 is a helper file" && exit 1
[ "$1" = "$BASH_SOURCE" ] && show_usage $BASH_SOURCE

# set export variables
export STAGE="$2"
export TARGET="$(basename "$(find $DIR_CONF -type d -iname "$1" 2>/dev/null)" 2>/dev/null)"

# set local variables
local _STAGES=($(ls $DIR_STGS/$([ -n "$STAGE" ] && echo $STAGE* $DIR_STGS/[0-9][0-9]-$STAGE*) 2>/dev/null))
local _START=$(basename "${_STAGES[0]}")
local _STARTED=0

[ -z "$TARGET" ] && show_error "'$1' is not a valid target" $BASH_SOURCE

show_header

# loop through stages only do from starting stage
for FILE_STAGE in $(ls $DIR_STGS); do
  [ "$FILE_STAGE" = "$_START" ] && _STARTED=1
  [ $_STARTED = 1 ] && indigen stage $FILE_STAGE $TARGET
done | cat
