#!/bin/bash
#@aboriginal clean [target]
#@ - Clean a specific target to prepare for rebuild
[ -z $VER ] && echo "$0 is a helper file" && exit 1
[ "$1" = "$(basename $BASH_SOURCE)" ] && show_usage $BASH_SOURCE
