#!/bin/bash
#@call config build
#@ - Configure Indigen Build System
#@call config [package]
#@ - Configure a specific package
#@call config [target]
#@ - Configure a specific target
#@call config [target] [package]
#@ - Configure a specific package for a specific target
[ -z $VER ] && echo "$0 is a helper file" && exit 1
[ "$1" = "$BASH_SOURCE" ] && show_usage $BASH_SOURCE
[ -z "$EDITOR" ] && EDITOR=nano
[ -n "$2" ] && [ -f "$DIR_CONF/$1/$2.conf" ] && $EDITOR "$DIR_CONF/$1/$2.conf" && exit
[ -f "$DIR_CONF/$1.conf" ] && $EDITOR "$DIR_CONF/$1.conf" && exit
[ -f "$DIR_CONF/$1/build.conf" ] && $EDITOR "$DIR_CONF/$1/build.conf" && exit
echo "There are no config files for $1. To create a package or target try:"
echo
echo "  $EDITOR $DIR_CONF/$1.conf"
echo
echo "  $EDITOR $DIR_CONF/$1/build.conf"
echo
exit
