#!/bin/bash
#@call help [topic]
#@ - View help for specific topic
[ -z $VER ] && echo "$0 is a helper file" && exit 1
[ "$1" = "$BASH_SOURCE" ] && show_usage $BASH_SOURCE

show_header
echo "  $CALL help $1"
echo

man $DIR_HELP/$1

exit
