#!/bin/bash
#@call list [type]
#@ - List shortcuts and commands
[ -z $VER ] && echo "$0 is a helper file" && exit 1
[ "$1" = "$BASH_SOURCE" ] && show_usage $BASH_SOURCE
[ -z "$(declare -F list_$1)" ] && show_error "list '$1' does not exist" $BASH_SOURCE

show_header
list_$1

