#!/bin/bash
#@aboriginal sandbox [stage]
#@ - Sandbox a command or script
[ -z $VER ] && echo "$0 is a helper file" && exit 1
[ "$1" = "$(basename $BASH_SOURCE)" ] && show_usage $BASH_SOURCE

echo "Hello Tarah!"
