#!/bin/bash
[ -z $VER ] && echo "$0 is a helper file" && exit 1

download_if_needed() {
  [ -z "$URL" ] && return 0

  local FILENAME="$(basename $URL)"
  local FILEPATH="$DIR_CODE/$FILENAME"

  download_checksum $FILEPATH $SHA1 && return 0

  echo -ne "  Downloading $CONFIG from $URL"
  wget  --quiet -t 2 -T 20 -O "$FILEPATH" "$URL" > /dev/null || (rm -f "$FILEPATH"; return 500)
  echo -ne "\r"

  download_checksum $FILEPATH $SHA1 && return 0

  echo -ne "  FAILED VERIFICATION - $FILEPATH\n" && exit 1
}

download_checksum() {
  [ ! -f "$1" ] && return 1
  [ -z "$2" ] && echo -ne "  UNVERIFIED - $CONFIG\n" && return 0
  [ -z "$(which sha1sum)" ] && show_error "  Install sha1sum to verify files" $BASH_SOURCE

  SUM="$(sha1sum "$1"  2>/dev/null | sed 's/\s.*$//')"

  [ x"$SUM" == x"$2" ] && echo -ne "  VERIFIED - $CONFIG\n" && return 0

  rm -f $1

  return 1
}

build_config download_if_needed
