#!/bin/bash
[ -z $VER ] && echo "$0 is a helper file" && exit 1

hosttools_build() {
  [ "$BUILD_HOST" = "true" ] && return 0
  [ -z "$FORK" ] && echo -ne "  \E[33mBuilding host version of $CONFIG\E[0m\n"

  [ ! -f "$DIR_HOST/$CONFIG" ] && build_section $CONFIG
}

hosttools_path() {
  local X

  echo -n "$DIR_HOST"
  X=1
  while [ -e "$DIR_HOST/fallback-$X" ]; do
    echo -n ":$DIR_HOST/fallback-$X"
    X=$[$X+1]
  done
}

hosttools_symlink() {
  rm -rf "$DIR_HOST/*" 2>&1 >/dev/null

  # Create symlinks to the host toolchain.  We need a usable existing host
  # toolchain in order to build anything else (even a new host toolchain),
  # and we don't really want to have to care what the host type is, so
  # just use the toolchain that's already there.

  # This is a little more complicated than it needs to be, because the host
  # toolchain may be using ccache and/or distcc, which means we need every
  # instance of these tools that occurs in the $PATH, in order, each in its
  # own fallback directory.

  for i in ar as nm cc make ld gcc $HOST_EXTRA; do
    if [ ! -f "$DIR_HOST/$x" ]; then
      # Loop through each instance, populating fallback directories.
  
      i=0
      FALLBACK="$DIR_HOST"
      PATH="$SAVEPATH" "$DIR_HOST/which" -a "$x" | while read xx; do
        if [ ! -e "$FALLBACK/$x" ]; then
          mkdir -p "$FALLBACK" &&
          ln -sf "$xx" "$FALLBACK/$x" || oops
        fi
  
        i=$[$i+1]
        FALLBACK="$DIR_HOST/fallback-$i"
      done
  
      if [ ! -f "$STAGE_DIR/$x" ]; then
        show_error "Toolchain component missing: $x" help
      fi
    fi
  done

  # Workaround for a bug in Ubuntu 10.04 where gcc became a perl script calling
  # gcc.real.  Systems that aren't crazy don't need this.

  UBUNTUCC="$(PATH="$SAVEPATH" "$DIR_HOST/which" gcc.real)"
  [ ! -z "$UBUNTUCC" ] && ln -s "$UBUNTUCC" "$DIR_HOST/gcc.real" 2>/dev/null
}

build_config hosttools_build busybox
build_config hosttools_build toybox
hosttools_symlink
PATH="$(hosttools_path)"
build_config hosttools_build distccd
build_config hosttools_build genext2fs
build_config hosttools_build e2fprogs
build_config hosttools_build mke2fs
build_config hosttools_build zlib
build_config hosttools_build mksquashfs
